name: Lychee Link Check

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lychee-checks:
    name: Check Links
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - uses: actions/checkout@v4

      - name: Lychee Link Checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: --config ./lychee.toml .
          fail: true
